// Question bank: 6 questions per topic (level 1 = complete beginner, level 8
// = applied modern AI). Each question is tagged with the topic it belongs
// to. Used two ways: the placement diagnostic samples a few adaptively; the
// per-topic Deep Check (TopicDeepCheck.jsx) uses the full set for that topic.
export const questions = {
  1: [ // Python Basics
    { id: "p1", topic: "python-basics", prompt: "What does len([1, 2, 3]) return?", options: ["2", "3", "1", "Error"], answer: "3", explanation: "len() counts the elements in a list — there are three: 1, 2, 3." },
    { id: "p2", topic: "python-basics", prompt: "Which keyword defines a function in Python?", options: ["func", "function", "def", "lambda"], answer: "def", explanation: "def name(): starts a function definition; lambda makes an anonymous one-liner, not a named function." },
    { id: "p3", topic: "python-basics", prompt: "What does a Python dictionary store?", options: ["Only numbers, in order", "Key-value pairs", "A single value", "Only strings"], answer: "Key-value pairs", explanation: "A dict maps each key to an associated value, like {'name': 'Ana'} — lookups happen by key, not position." },
    { id: "p4", topic: "python-basics", prompt: "What's the key difference between a list and a tuple?", options: ["Tuples can't hold numbers", "Lists are mutable (can change), tuples are immutable (can't)", "Lists are faster in every case", "There is no real difference"], answer: "Lists are mutable (can change), tuples are immutable (can't)", explanation: "Once created, a tuple's contents can't be changed — you can append/remove/modify a list's contents freely." },
    { id: "p5", topic: "python-basics", prompt: "What does `for x in [1, 2, 3]:` do?", options: ["Runs the block once", "Runs the block three times, x taking each value in turn", "Creates a new list", "Causes an error"], answer: "Runs the block three times, x taking each value in turn", explanation: "A for loop over a list iterates once per element, binding x to 1, then 2, then 3." },
    { id: "p6", topic: "python-basics", prompt: "What does f\"Hi {name}\" do if name = \"Ana\"?", options: ["Prints the literal text {name}", "Produces the string \"Hi Ana\"", "Raises a syntax error", "Prints \"Hi name\""], answer: "Produces the string \"Hi Ana\"", explanation: "An f-string substitutes the value of the variable inside {} directly into the string." },
  ],
  2: [ // Data & Math for ML
    { id: "d1", topic: "data-math", prompt: "What does a NumPy array's .shape attribute describe?", options: ["Its data type", "Its dimensions", "Its memory address", "Its sort order"], answer: "Its dimensions", explanation: ".shape returns a tuple giving the size along each axis, e.g. (100, 3) for 100 rows and 3 columns." },
    { id: "d2", topic: "data-math", prompt: "What is the dot product of two orthogonal (perpendicular) vectors?", options: ["1", "Their magnitudes multiplied", "0", "Undefined"], answer: "0", explanation: "Orthogonal vectors have no component in each other's direction, so their dot product is always exactly 0." },
    { id: "d3", topic: "data-math", prompt: "What does the \"mean\" of a dataset measure?", options: ["The most frequent value", "The middle value when sorted", "The average value", "The spread of values"], answer: "The average value", explanation: "Mean = sum of all values divided by how many there are. Mode is most frequent, median is the middle value." },
    { id: "d4", topic: "data-math", prompt: "What does NumPy broadcasting let you do?", options: ["Send arrays over a network", "Apply operations across arrays of different but compatible shapes", "Convert arrays to lists", "Multiply matrices of any mismatched shape"], answer: "Apply operations across arrays of different but compatible shapes", explanation: "Broadcasting lets a smaller array be automatically stretched to match a larger one during arithmetic, without copying data." },
    { id: "d5", topic: "data-math", prompt: "What does standard deviation measure?", options: ["The average value", "How spread out the values are from the mean", "The most common value", "The total count of values"], answer: "How spread out the values are from the mean", explanation: "A small standard deviation means values cluster close to the mean; a large one means they're spread widely." },
    { id: "d6", topic: "data-math", prompt: "To multiply matrix A (shape m×n) by matrix B, what must B's shape be?", options: ["Any shape at all", "n×p — inner dimensions must match", "m×n, identical to A", "p×m only"], answer: "n×p — inner dimensions must match", explanation: "Matrix multiplication requires the number of columns in A to equal the number of rows in B." },
  ],
  3: [ // Core ML Concepts
    { id: "m1", topic: "ml-foundations", prompt: "In supervised learning, what is a \"label\"?", options: ["A comment in the code", "The correct answer the model is trained to predict", "A type of neural network", "The learning rate"], answer: "The correct answer the model is trained to predict", explanation: "Supervised learning trains on (input, label) pairs — the label is the ground-truth output the model learns to reproduce." },
    { id: "m2", topic: "ml-foundations", prompt: "What does \"overfitting\" mean?", options: ["The model trains too slowly", "The model fits training data too closely and fails on new data", "The model uses too little memory", "The dataset is too large"], answer: "The model fits training data too closely and fails on new data", explanation: "An overfit model has essentially memorized noise in the training set, so it performs well there but poorly on unseen data." },
    { id: "m3", topic: "ml-foundations", prompt: "Why do we split data into training and test sets?", options: ["To make training faster", "To evaluate how well the model generalizes to unseen data", "To reduce storage costs", "It's only needed for deep learning"], answer: "To evaluate how well the model generalizes to unseen data", explanation: "The model never sees the test set during training, so performance there estimates how it'll do on real, new inputs." },
    { id: "m4", topic: "ml-foundations", prompt: "What is a \"feature\" in a machine learning dataset?", options: ["A bug in the model", "An input variable used to make predictions", "The final prediction itself", "A type of neural network layer"], answer: "An input variable used to make predictions", explanation: "Features are the measurable inputs (e.g. square footage, age) a model uses to predict a label (e.g. house price)." },
    { id: "m5", topic: "ml-foundations", prompt: "What does \"underfitting\" mean?", options: ["The model is too complex", "The model is too simple to capture the real pattern, performing poorly even on training data", "The model trained for too long", "The dataset is too clean"], answer: "The model is too simple to capture the real pattern, performing poorly even on training data", explanation: "An underfit model hasn't learned enough — the opposite problem from overfitting." },
    { id: "m6", topic: "ml-foundations", prompt: "What is cross-validation used for?", options: ["Speeding up training", "Getting a more reliable estimate of model performance by testing on multiple data splits", "Cleaning missing data", "Visualizing a neural network"], answer: "Getting a more reliable estimate of model performance by testing on multiple data splits", explanation: "Instead of one train/test split, cross-validation rotates through several splits and averages the results, reducing the chance of a lucky or unlucky split." },
  ],
  4: [ // Regression & Gradient Descent
    { id: "r1", topic: "regression-gd", prompt: "What does gradient descent do?", options: ["Randomly guesses parameters until one works", "Iteratively adjusts parameters to minimize a loss function", "Sorts the training data", "Removes outliers from the dataset"], answer: "Iteratively adjusts parameters to minimize a loss function", explanation: "It repeatedly nudges each parameter in the direction that reduces the loss, using the gradient (slope) of the loss with respect to that parameter." },
    { id: "r2", topic: "regression-gd", prompt: "In linear regression, what is the model trying to find?", options: ["The largest value in the dataset", "The line (weights) that best fits the data", "A list of all possible outputs", "The number of training examples"], answer: "The line (weights) that best fits the data", explanation: "Linear regression fits a straight-line (or hyperplane) relationship between inputs and output, choosing weights that minimize prediction error." },
    { id: "r3", topic: "regression-gd", prompt: "What does the \"learning rate\" control in gradient descent?", options: ["How much data is used per step", "The size of each parameter-update step", "The number of layers in the model", "How the data is split"], answer: "The size of each parameter-update step", explanation: "Too high and training can overshoot and diverge; too low and training crawls." },
    { id: "r4", topic: "regression-gd", prompt: "What does a \"loss function\" measure?", options: ["How fast the model runs", "How wrong the model's predictions currently are", "How much memory the model uses", "The number of training examples"], answer: "How wrong the model's predictions currently are", explanation: "Training is the process of adjusting parameters to make the loss function's value as small as possible." },
    { id: "r5", topic: "regression-gd", prompt: "What does it mean when gradient descent has \"converged\"?", options: ["Training crashed", "The loss has stopped decreasing meaningfully — parameters have settled near a minimum", "The dataset ran out", "The learning rate hit zero by force"], answer: "The loss has stopped decreasing meaningfully — parameters have settled near a minimum", explanation: "Convergence means further steps barely change the loss — the model has found a good (if not always perfect) set of parameters." },
    { id: "r6", topic: "regression-gd", prompt: "What is \"regularization\" used for?", options: ["Speeding up data loading", "Penalizing overly large weights to reduce overfitting", "Increasing model accuracy on training data only", "Normalizing file formats"], answer: "Penalizing overly large weights to reduce overfitting", explanation: "By adding a penalty for large weights to the loss, regularization discourages the model from fitting noise too closely." },
  ],
  5: [ // Neural Network Basics
    { id: "n1", topic: "neural-nets", prompt: "What is the role of an activation function in a neural network?", options: ["It stores the training data", "It introduces non-linearity so the network can learn complex patterns", "It splits data into batches", "It only runs during testing"], answer: "It introduces non-linearity so the network can learn complex patterns", explanation: "Without a non-linear activation (like ReLU), stacking layers would collapse into one big linear function." },
    { id: "n2", topic: "neural-nets", prompt: "What does backpropagation compute?", options: ["The final test accuracy", "Gradients of the loss with respect to each weight, to update them", "The number of training epochs needed", "A summary of the dataset"], answer: "Gradients of the loss with respect to each weight, to update them", explanation: "It applies the chain rule backward through the network to figure out how much each weight contributed to the error." },
    { id: "n3", topic: "neural-nets", prompt: "What is a \"perceptron\"?", options: ["A dataset format", "The simplest neural network unit — a weighted sum plus bias", "A type of loss function", "A GPU optimization technique"], answer: "The simplest neural network unit — a weighted sum plus bias", explanation: "A perceptron multiplies inputs by weights, adds a bias, and applies an activation — the basic building block layers stack together." },
    { id: "n4", topic: "neural-nets", prompt: "What is a \"hidden layer\"?", options: ["A layer that's deliberately hidden from the user in a UI", "Any layer between the input and output layers", "The final output layer only", "A layer with no weights"], answer: "Any layer between the input and output layers", explanation: "Hidden layers do the internal computation — a network with more of them can learn more complex representations." },
    { id: "n5", topic: "neural-nets", prompt: "What does the ReLU activation function do?", options: ["Outputs 0 for negative inputs, the input itself for positive ones", "Always outputs a value between 0 and 1", "Reverses the input sign", "Only works on images"], answer: "Outputs 0 for negative inputs, the input itself for positive ones", explanation: "ReLU (Rectified Linear Unit) is max(0, x) — simple, fast, and the most common activation in modern networks." },
    { id: "n6", topic: "neural-nets", prompt: "What is a \"weight\" in a neural network?", options: ["The size of the training dataset", "A learned number controlling how strongly one neuron's output affects the next", "The number of layers", "The batch size used in training"], answer: "A learned number controlling how strongly one neuron's output affects the next", explanation: "Weights are exactly what gradient descent adjusts during training — they're the network's learned parameters." },
  ],
  6: [ // Deep Learning Practice
    { id: "l1", topic: "deep-learning", prompt: "What is a convolutional layer especially good at?", options: ["Sorting text alphabetically", "Detecting spatial patterns like edges and shapes in images", "Storing data in a database", "Compressing audio files"], answer: "Detecting spatial patterns like edges and shapes in images", explanation: "Convolutional filters slide across an image detecting local patterns, which is why CNNs dominate computer vision." },
    { id: "l2", topic: "deep-learning", prompt: "What does one \"epoch\" mean in training?", options: ["One single training example", "One full pass through the entire training dataset", "One layer in the network", "One second of training time"], answer: "One full pass through the entire training dataset", explanation: "Models typically train for many epochs, seeing the full dataset repeatedly so weights keep improving." },
    { id: "l3", topic: "deep-learning", prompt: "Training loss is stuck and not decreasing at all — what's a likely cause?", options: ["Too much training data", "Learning rate badly tuned (too high or too low) or bad initialization", "The model is too accurate already", "The test set is too small"], answer: "Learning rate badly tuned (too high or too low) or bad initialization", explanation: "A learning rate that's too high can make training diverge; too low and it barely moves — both look like \"stuck\" loss." },
    { id: "l4", topic: "deep-learning", prompt: "What is \"batch size\"?", options: ["The total size of the dataset", "The number of training examples processed before one weight update", "The number of layers in the model", "The size of the model file on disk"], answer: "The number of training examples processed before one weight update", explanation: "Instead of updating weights after every single example, most training updates after a batch — a tradeoff between speed and stability." },
    { id: "l5", topic: "deep-learning", prompt: "What does \"dropout\" do during training?", options: ["Deletes bad training examples", "Randomly disables some neurons each step, to reduce overfitting", "Stops training early", "Removes an entire layer permanently"], answer: "Randomly disables some neurons each step, to reduce overfitting", explanation: "By forcing the network not to rely too heavily on any single neuron, dropout acts as a form of regularization." },
    { id: "l6", topic: "deep-learning", prompt: "What is \"transfer learning\"?", options: ["Moving a model to a different GPU", "Reusing a model already trained on one task as the starting point for a related task", "Copying training data between projects", "Converting a model to a different programming language"], answer: "Reusing a model already trained on one task as the starting point for a related task", explanation: "This is exactly what the Sandbox tab does with MobileNet — starting from a model that already understands images, instead of training from zero." },
  ],
  7: [ // Transformers & Attention
    { id: "t1", topic: "transformers", prompt: "What mechanism lets transformers weigh the importance of different input tokens relative to each other?", options: ["Convolution", "Self-attention", "Max pooling", "Batch normalization"], answer: "Self-attention", explanation: "Self-attention lets every token look at every other token and decide how much to weight it — the core innovation behind transformers." },
    { id: "t2", topic: "transformers", prompt: "Why are transformers easier to parallelize during training than older RNNs?", options: ["They use less memory overall", "They process all tokens simultaneously instead of one at a time in sequence", "They don't need GPUs", "They have fewer parameters"], answer: "They process all tokens simultaneously instead of one at a time in sequence", explanation: "RNNs process tokens step-by-step, which is inherently sequential. Transformers process a whole sequence at once." },
    { id: "t3", topic: "transformers", prompt: "What is a \"token\" in the context of a language model?", options: ["A single training run", "A chunk of text (a word or sub-word piece) the model processes as one unit", "A type of neural network layer", "A GPU core"], answer: "A chunk of text (a word or sub-word piece) the model processes as one unit", explanation: "Text is broken into tokens before being fed to the model — often sub-word pieces." },
    { id: "t4", topic: "transformers", prompt: "Since self-attention has no built-in sense of word order, what fixes that?", options: ["Nothing — order doesn't matter to transformers", "Positional encoding, added to each token to represent its position", "A separate ordering neural network", "Sorting the tokens alphabetically first"], answer: "Positional encoding, added to each token to represent its position", explanation: "Without positional encoding, \"dog bites man\" and \"man bites dog\" would look identical to the attention mechanism." },
    { id: "t5", topic: "transformers", prompt: "What does \"multi-head attention\" mean?", options: ["Running the model on multiple GPUs", "Running several attention computations in parallel, each learning different relationships", "Attention that only works on multiple-choice questions", "A model with multiple output layers"], answer: "Running several attention computations in parallel, each learning different relationships", explanation: "Each \"head\" can specialize — one might track grammar, another might track long-range topic relationships." },
    { id: "t6", topic: "transformers", prompt: "What does \"pretraining\" a transformer mean?", options: ["Testing the model before deployment", "Training it on a large, general corpus before any specific task", "Manually setting all its weights by hand", "Compressing the model to run faster"], answer: "Training it on a large, general corpus before any specific task", explanation: "Pretraining builds general language understanding; fine-tuning (a later topic) then specializes it for a specific job." },
  ],
  8: [ // Applied LLMs & RAG
    { id: "a1", topic: "llms-applied", prompt: "What does RAG (Retrieval-Augmented Generation) do?", options: ["Trains a model from scratch faster", "Grounds an LLM's output in real, retrieved documents instead of relying only on memorized knowledge", "Reduces a model's parameter count", "Converts text to speech"], answer: "Grounds an LLM's output in real, retrieved documents instead of relying only on memorized knowledge", explanation: "RAG searches a real document store for relevant content and feeds it to the model as context — exactly what the Plan tab does." },
    { id: "a2", topic: "llms-applied", prompt: "What is \"fine-tuning\" a model?", options: ["Deleting part of the model", "Further training a pretrained model on a smaller, task-specific dataset", "Changing only the model's file format", "Running the model faster on a GPU"], answer: "Further training a pretrained model on a smaller, task-specific dataset", explanation: "Instead of training from scratch, fine-tuning adapts an already-capable pretrained model using far less data and compute." },
    { id: "a3", topic: "llms-applied", prompt: "What is a \"prompt\" when using a large language model?", options: ["The model's internal weight values", "The input text/instructions given to the model to produce a response", "A type of loss function", "The GPU used for inference"], answer: "The input text/instructions given to the model to produce a response", explanation: "The prompt is everything you feed the model as input — instructions, context, examples — that shapes what it generates back." },
    { id: "a4", topic: "llms-applied", prompt: "What is a model's \"context window\"?", options: ["The physical screen showing its output", "The maximum amount of text it can consider at once", "A setting for image resolution", "The time it takes to respond"], answer: "The maximum amount of text it can consider at once", explanation: "Anything beyond the context window limit simply isn't visible to the model when generating its next response." },
    { id: "a5", topic: "llms-applied", prompt: "What does \"hallucination\" mean for an LLM?", options: ["The model crashes", "The model generates confident-sounding but false or fabricated information", "The model refuses to answer", "The model runs out of memory"], answer: "The model generates confident-sounding but false or fabricated information", explanation: "This is exactly the failure mode RAG is designed to reduce — by grounding answers in real retrieved text instead of pure memory." },
    { id: "a6", topic: "llms-applied", prompt: "What does the \"temperature\" setting control when generating text?", options: ["How fast the model responds", "How random vs. predictable the output is", "The physical GPU temperature", "The maximum output length"], answer: "How random vs. predictable the output is", explanation: "Low temperature makes output more deterministic and focused; high temperature makes it more varied and creative." },
  ],
};
